const grid = {
  DI: { x: 1, y: 1 },
  HI: { x: 2, y: 4 },
  LA: { x: 1, y: 4 },
  RD: { x: 5, y: 7 },
  TA: { x: 4, y: 6 },
  QU: { x: 4, y: 5 },
  SU: { x: 7, y: 3 },
  HA: { x: 7, y: 6 },
  RA: { x: 6, y: 5 },
  HL: { x: 6, y: 7 },
  DY: { x: 2, y: 5 },
  DR: { x: 0, y: 3 },
  HM: { x: 6, y: 8 },
  IB: { x: 3, y: 4 }
  // SN: { x: 4, y: 4 },
  // SX: { x: 5, y: 4 },
  // HU: { x: 5, y: 5 },
  // HN: { x: 5, y: 6 },
  // SC: { x: 3, y: 5 },
  // YN: { x: 3, y: 6 },
  // HB: { x: 6, y: 3 },
  // HA: { x: 6, y: 4 },
  // LN: { x: 7, y: 2 },
  // SD: { x: 8, y: 3 },
  // TJ: { x: 9, y: 3 },
  // JX: { x: 6, y: 6 },
  // JS: { x: 7, y: 4 },
  // SH: { x: 8, y: 4 },
  // ZJ: { x: 7, y: 5 },
  // JL: { x: 8, y: 2 },
  // NM: { x: 6, y: 2 },
  // HK: { x: 9, y: 1 }
}

export default grid
