const grid = {
  AV: { x: 1, y: 1 },
  GS: { x: 2, y: 4 },
  QH: { x: 1, y: 4 },
  GX: { x: 5, y: 7 },
  GZ: { x: 4, y: 6 },
  CQ: { x: 4, y: 5 },
  BJ: { x: 7, y: 3 },
  FJ: { x: 7, y: 6 },
  AH: { x: 6, y: 5 },
  GD: { x: 6, y: 7 },
  XZ: { x: 2, y: 5 },
  XJ: { x: 0, y: 3 },
  HI: { x: 6, y: 8 },
  NX: { x: 3, y: 4 },
  SN: { x: 4, y: 4 },
  SX: { x: 5, y: 4 },
  HU: { x: 5, y: 5 },
  HN: { x: 5, y: 6 },
  SC: { x: 3, y: 5 },
  YN: { x: 3, y: 6 },
  HB: { x: 6, y: 3 },
  HA: { x: 6, y: 4 },
  LN: { x: 7, y: 2 },
  SD: { x: 8, y: 3 },
  TJ: { x: 9, y: 3 },
  JX: { x: 6, y: 6 },
  JS: { x: 7, y: 4 },
  SH: { x: 8, y: 4 },
  ZJ: { x: 7, y: 5 },
  JL: { x: 8, y: 2 },
  NM: { x: 6, y: 2 },
  HK: { x: 9, y: 1 }
}

export default grid
